"""Generate docs/PHASE3_ENRICHMENT.md from committed enrichment data (NEWS-07, NEWS-08,
REV-02).

Usage (from the repo root, no network):
    python -m scripts.report_phase3
    python -m scripts.report_phase3 --stdout --episode-ids 2020-03-09_shock,2022-06-13_drawdown

Every number is read from data/episodes.parquet, data/events.json,
data/event_overrides.json and data/enrichment_spend.json (or the --*-path overrides)
through core.storage -- never hand-typed, per CLAUDE.md's honesty rule. Safe to run
before any real enrichment data exists: with no committed events.json this reports 0
current records and still exits 0 (03-06 runs the real backfill that gives this report
something to say). Do not hand-edit docs/PHASE3_ENRICHMENT.md.
"""
from __future__ import annotations

import argparse
import json
import os
from collections import Counter
from pathlib import Path

from core.config import ROOT, SETTINGS
from core.news.cost import ledger_total_usd
from core.news.overrides import Override, apply_overrides
from core.news.schema import is_current_record
from core.storage import load_episodes, load_event_overrides, load_events, load_spend_ledger

OUTPUT_PATH = ROOT / "docs" / "PHASE3_ENRICHMENT.md"
HEADER = "Generated by `python -m scripts.report_phase3`. Do not hand-edit."

# Patterns that must never appear in committed enrichment data (NEWS-05's "no stored
# article text beyond what's needed" rule and OPS-03's "key never leaks" rule). Checked
# case-insensitively, matching tests/test_events_data.py's committed-file scan.
_LEAK_SUBSTRINGS = ("sk-ant-", "x-api-key", "encrypted_content", "cited_text")


def _leak_scan(texts: list[str], settings) -> bool:
    """True (PASS) iff none of `texts` contains a leaked secret or copyright pattern.
    The current ANTHROPIC_API_KEY env value (if set) is checked but its value is never
    included in the rendered report."""
    combined = "\n".join(texts)
    lowered = combined.lower()
    if any(pattern in lowered for pattern in _LEAK_SUBSTRINGS):
        return False
    env_value = os.environ.get(settings.anthropic_api_key_env, "")
    return not (env_value and env_value in combined)


def _counter_section(title: str, counts: Counter) -> list[str]:
    lines = [f"### {title}", ""]
    if not counts:
        return lines + ["(none)", ""]
    lines += ["| Value | Count |", "| --- | --- |"]
    for key, count in sorted(counts.items(), key=lambda kv: str(kv[0])):
        lines.append(f"| {key} | {count} |")
    lines.append("")
    return lines


def render_enrichment_report(
    episodes: list[dict],
    records: list[dict],
    overrides: list[Override],
    ledger: list[dict],
    settings,
) -> str:
    """Render docs/PHASE3_ENRICHMENT.md's content. Pure -- no I/O. `episodes` is a list
    of dicts with at least episode_id/status; `records` is the raw data/events.json
    records list; `overrides` are parsed Override models; `ledger` is the raw
    data/enrichment_spend.json runs list."""
    closed_ids = {ep["episode_id"] for ep in episodes if ep.get("status") == "closed"}
    current_records = [
        r for r in records if is_current_record(r, settings.news_prompt_version)
    ]
    current_ids = {r["episode_id"] for r in current_records}
    missing_ids = sorted(closed_ids - current_ids)

    effective = apply_overrides(current_records, overrides)

    raw_status = Counter(r.get("status") for r in current_records)
    effective_status = Counter(r.get("status") for r in effective)
    reviewed_count = sum(1 for r in effective if r.get("reviewed"))
    rejected_count = sum(1 for r in effective if r.get("rejected"))
    unresolved_needs_review = sorted(
        r["episode_id"] for r in effective if r.get("status") == "needs_review"
    )

    records_per_model = Counter(r.get("model") for r in current_records)

    dropped_reason_tally: Counter = Counter()
    stop_reason_tally: Counter = Counter()
    search_counts: list[int] = []
    for r in current_records:
        for dropped in r.get("dropped_sources") or []:
            dropped_reason_tally[dropped.get("reason")] += 1
        for reason in r.get("stop_reasons") or []:
            stop_reason_tally[reason] += 1
        search_counts.append((r.get("usage") or {}).get("web_search_requests", 0))
    total_searches = sum(search_counts)
    max_searches = max(search_counts) if search_counts else 0

    ledger_total = ledger_total_usd(ledger)

    leak_ok = _leak_scan(
        [
            json.dumps(records, default=str),
            json.dumps([o.model_dump(mode="json") for o in overrides]),
            json.dumps(ledger, default=str),
        ],
        settings,
    )

    lines = ["# Phase 3 enrichment report", "", HEADER, ""]
    lines += [
        "## Coverage",
        "",
        f"Closed episodes: {len(closed_ids)}",
        f"Current records: {len(current_records)}",
        f"Missing: {len(missing_ids)}",
        "",
    ]
    if missing_ids:
        lines += ["Missing episode_ids:"] + [f"- {eid}" for eid in missing_ids] + [""]

    lines += _counter_section("Raw status counts", raw_status)
    lines += _counter_section("Effective status counts (after overrides)", effective_status)
    lines += [f"Reviewed: {reviewed_count}", f"Rejected: {rejected_count}", ""]

    lines += ["### Unresolved needs_review", ""]
    lines += (
        [f"- {eid}" for eid in unresolved_needs_review] if unresolved_needs_review else ["(none)"]
    )
    lines.append("")

    lines += _counter_section("Records per model", records_per_model)
    lines += _counter_section("Dropped-source reasons", dropped_reason_tally)
    lines += _counter_section("Stop reasons", stop_reason_tally)

    lines += [
        "## Web search usage",
        "",
        f"Total requests: {total_searches}",
        f"Max per episode: {max_searches}",
        "",
    ]
    lines += [
        "## Spend",
        "",
        f"Ledger total: ${ledger_total:.2f}",
        f"Budget: ${settings.news_budget_usd:.2f}",
        "",
    ]
    lines += ["## Leak scan", "", "PASS" if leak_ok else "FAIL", ""]

    return "\n".join(lines) + "\n"


def render_episode_table(records: list[dict], episode_ids: list[str]) -> str:
    """One row per `episode_ids` entry: status, confidence, kept source count, dropped
    reasons, searches, cost_usd, headline. An id with no matching record shows
    "missing" for every column."""
    records_by_id = {r["episode_id"]: r for r in records}
    lines = [
        (
            "| episode_id | status | confidence | kept_sources | dropped_reasons | "
            "searches | cost_usd | headline |"
        ),
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for episode_id in episode_ids:
        record = records_by_id.get(episode_id)
        if record is None:
            lines.append(f"| {episode_id} | missing | missing | missing | missing | "
                          "missing | missing | missing |")
            continue
        kept = len(record.get("sources") or [])
        dropped_reasons = sorted({d.get("reason") for d in (record.get("dropped_sources") or [])})
        searches = (record.get("usage") or {}).get("web_search_requests", 0)
        lines.append(
            f"| {episode_id} | {record.get('status')} | {record.get('confidence')} | "
            f"{kept} | {', '.join(dropped_reasons)} | {searches} | "
            f"{record.get('cost_usd', 0.0):.4f} | {record.get('headline', '')} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--events-path", default=str(SETTINGS.events_path))
    parser.add_argument("--overrides-path", default=str(SETTINGS.event_overrides_path))
    parser.add_argument("--episodes-path", default=str(SETTINGS.episodes_path))
    parser.add_argument("--ledger-path", default=str(SETTINGS.news_spend_ledger_path))
    parser.add_argument("--out", default=str(OUTPUT_PATH))
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument(
        "--episode-ids", default="", help="comma-separated episode_ids for a spike table"
    )
    args = parser.parse_args(argv)

    try:
        episodes_df = load_episodes(Path(args.episodes_path))
        episodes = episodes_df[["episode_id", "status"]].to_dict("records")
    except OSError:
        episodes = []

    records = load_events(Path(args.events_path), missing_ok=True)
    overrides = load_event_overrides(Path(args.overrides_path))
    ledger = load_spend_ledger(Path(args.ledger_path))

    report = render_enrichment_report(episodes, records, overrides, ledger, SETTINGS)

    if args.episode_ids:
        episode_ids = [e for e in args.episode_ids.split(",") if e]
        print(render_episode_table(records, episode_ids))

    if args.stdout:
        print(report)
        return 0

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
