"""Generate docs/PHASE2_CALIBRATION.md from the committed Phase 2 artifacts (DET-06).

Usage (from the repo root, no network):
    python -m scripts.report_phase2

Every number below is read from data/episodes.parquet, data/macro_calendar.parquet or
core.config.SETTINGS -- never hand-typed, per CLAUDE.md's honesty rule ("every reported
figure regenerated by a script, not hand-edited"). Re-run after any plan that changes
core/events.py, core/calendar.py or the committed data/ artifacts; do not hand-edit
docs/PHASE2_CALIBRATION.md.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from core.config import ROOT, SETTINGS
from core.storage import load_episodes, load_macro_calendar

OUTPUT_PATH = ROOT / "docs" / "PHASE2_CALIBRATION.md"

# DET-07: the seven known episodes this detector must find. Defined here as the single
# source of truth; tests/test_detect_events.py imports this exact dict so the probe list
# can never silently drift between the test and this report.
KNOWN_EPISODES: dict[str, str] = {
    "2000-02": "2002-07-23",
    "2008": "2008-10-09",
    "Aug 2015": "2015-08-24",
    "Feb 2018": "2018-02-05",
    "Q4 2018": "2018-12-24",
    "Mar 2020": "2020-03-16",
    "2022": "2022-06-13",
}

# Settings fields under the "Event detection (DET-01..07)" and "Macro calendar
# (CAL-01..02)" sections of core/config.py, plus detector_version -- the complete set of
# thresholds this phase calibrates. Field *names* are listed deliberately (not
# auto-discovered from the dataclass) so an unrelated future Settings field never
# silently appears in, or disappears from, this report.
DET_FIELDS: tuple[str, ...] = (
    "detector_version", "shock_sigma_window", "shock_z_threshold", "gap_threshold",
    "drawdown_threshold", "rally_threshold", "rally_window_days", "merge_window_days",
    "search_pre_days", "search_post_days", "structural_search_half_width",
    "severity_move_step", "trigger_precedence", "episode_count_bounds",
)
CAL_FIELDS: tuple[str, ...] = (
    "calendar_start", "calendar_first_release_by", "fred_releases",
    "fred_source_url_template", "fred_non_release_dates", "fred_double_release_months",
    "fomc_historical_url_template", "fomc_calendars_url", "http_timeout_s",
    "fomc_scheduled_per_year", "fomc_non_decision_meetings", "monthly_releases_per_year",
    "calendar_horizon_days",
)


def _fmt(value: object) -> str:
    """Fixed, deterministic rendering so reruns on unchanged data are byte-stable."""
    if isinstance(value, Path):
        return str(value.relative_to(ROOT)).replace("\\", "/")
    if isinstance(value, float):
        return f"{value:.6g}"
    return repr(value)


def _thresholds_section() -> list[str]:
    lines = [
        "## Thresholds",
        "",
        (
            "D-01: episodes cluster on the steepest leg -- drawdown peak->trough, "
            "rally trough->peak -- not the full peak-to-recovery span."
        ),
        "",
        "### Event detection (DET-01..07)",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    for field in DET_FIELDS:
        lines.append(f"| `{field}` | `{_fmt(getattr(SETTINGS, field))}` |")
    lines += [
        "",
        "### Macro calendar (CAL-01..02)",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    for field in CAL_FIELDS:
        lines.append(f"| `{field}` | `{_fmt(getattr(SETTINGS, field))}` |")
    lines.append("")
    return lines


def _counts_table(title: str, series: pd.Series) -> list[str]:
    out = [f"### {title}", "", "| Value | Count |", "| --- | --- |"]
    for key, count in series.value_counts().sort_index().items():
        out.append(f"| {key} | {count} |")
    out.append("")
    return out


def _episode_counts_section(episodes: pd.DataFrame) -> list[str]:
    lines = ["## Episode counts", "", f"Total: {len(episodes)}", ""]
    lines += _counts_table("By trigger", episodes["trigger"])
    lines += _counts_table("By status", episodes["status"])
    lines += _counts_table("By catalyst", episodes["catalyst"])
    lines += _counts_table("By direction", episodes["direction"])
    decade = (episodes["start_date"].dt.year // 10 * 10).astype(str) + "s"
    lines += _counts_table("Episodes per decade", decade)
    return lines


def _known_episodes_section(episodes: pd.DataFrame) -> list[str]:
    lines = [
        "## Known episodes (DET-07)",
        "",
        "| Label | Probe date | episode_id | Start | End | Trigger | move_pct | Catalyst |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for label, probe in KNOWN_EPISODES.items():
        probe_date = pd.Timestamp(probe)
        match = episodes[
            (episodes["start_date"] <= probe_date) & (probe_date <= episodes["end_date"])
        ]
        if len(match) != 1:
            raise ValueError(f"{label}: expected exactly one episode containing {probe}")
        row = match.iloc[0]
        lines.append(
            f"| {label} | {probe} | {row['episode_id']} | {row['start_date'].date()} | "
            f"{row['end_date'].date()} | {row['trigger']} | {row['move_pct']:.4f} | "
            f"{row['catalyst']} |"
        )
    lines.append("")
    return lines


def _calendar_coverage_section(calendar: pd.DataFrame) -> list[str]:
    lines = [
        "## Macro calendar coverage",
        "",
        "| Release | Count | First | Last |",
        "| --- | --- | --- | --- |",
    ]
    for release in sorted(calendar["release"].unique()):
        rows = calendar[calendar["release"] == release]
        lines.append(
            f"| {release} | {len(rows)} | {rows['date'].min().date()} | "
            f"{rows['date'].max().date()} |"
        )
    unscheduled_fomc = int(((calendar["release"] == "FOMC") & ~calendar["scheduled"]).sum())
    lines += ["", f"Unscheduled FOMC actions: {unscheduled_fomc}", ""]
    return lines


def build_report(episodes: pd.DataFrame, calendar: pd.DataFrame) -> str:
    lines = [
        "# Phase 2 calibration record",
        "",
        (
            "Generated by scripts/report_phase2.py -- do not hand-edit. Re-run after any "
            "plan that changes core/events.py, core/calendar.py or the committed data/ "
            "artifacts."
        ),
        "",
    ]
    lines += _thresholds_section()
    lines += _episode_counts_section(episodes)
    lines += _known_episodes_section(episodes)
    lines += _calendar_coverage_section(calendar)
    return "\n".join(lines) + "\n"


def main() -> int:
    episodes = load_episodes(SETTINGS.episodes_path)
    calendar = load_macro_calendar(SETTINGS.macro_calendar_path)
    report = build_report(episodes, calendar)
    OUTPUT_PATH.write_text(report, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
