"""Generate docs/PHASE3_BUDGET.md from core/config.py's verified news-pricing fields
(NEWS-07, success criterion 1, D-01).

Usage (from the repo root, no network):
    python -m scripts.report_news_budget

Every number below is read from core.config.SETTINGS or the committed spend ledger --
never hand-typed, per CLAUDE.md's honesty rule ("every reported figure regenerated by a
script, not hand-edited"). Prices are verified only as of SETTINGS.news_pricing_verified_on
against SETTINGS.news_pricing_sources: re-verify them against those source URLs before
any paid run more than ~14 days after that date (RESEARCH's validity window), and re-run
this script afterwards. Do not hand-edit docs/PHASE3_BUDGET.md.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from core.config import ROOT, SETTINGS
from core.news.cost import estimate_backfill_usd, ledger_total_usd
from core.storage import load_episodes, load_spend_ledger

OUTPUT_PATH = ROOT / "docs" / "PHASE3_BUDGET.md"

HEADER = "Generated by `python -m scripts.report_news_budget`. Do not hand-edit."

# Fraction of the backfill assumed to need a needs_review escalation re-run, for the
# escalation-scenario line item below. Not a SETTINGS threshold (it governs only this
# report's illustrative scenario, not any runtime behaviour).
_ESCALATION_FRACTION = 0.2


def _usd(value: float) -> str:
    return f"{value:.2f}"


def _estimate(n_episodes: int, model: str, settings) -> float:
    return estimate_backfill_usd(
        n_episodes,
        model,
        settings,
        settings.news_estimate_searches_per_episode,
        settings.news_estimate_input_tokens_per_episode,
        settings.news_estimate_output_tokens_per_episode,
    )


def _pricing_section(settings) -> list[str]:
    lines = [
        "## Verified pricing",
        "",
        f"Verified on {settings.news_pricing_verified_on} against:",
        "",
    ]
    lines += [f"- {url}" for url in settings.news_pricing_sources]
    lines += [
        "",
        "| Model | Input $/MTok | Output $/MTok |",
        "| --- | --- | --- |",
    ]
    for name, in_price, out_price in settings.news_model_prices_usd_per_mtok:
        lines.append(f"| `{name}` | ${_usd(in_price)} | ${_usd(out_price)} |")
    lines += [
        "",
        f"Web search: ${_usd(settings.news_web_search_usd_per_1k)} per 1,000 searches.",
        "",
    ]
    return lines


def _estimate_section(n_episodes: int, settings) -> list[str]:
    haiku_estimate = _estimate(n_episodes, settings.news_model, settings)
    worst_case_search = (
        n_episodes * settings.news_max_searches_per_request
        * settings.news_web_search_usd_per_1k / 1000
    )
    worst_case_reserve = n_episodes * settings.news_episode_cost_reserve_usd
    n_escalate = round(n_episodes * _ESCALATION_FRACTION)
    escalation_estimate = _estimate(n_escalate, settings.news_escalation_model, settings)

    return [
        "## Budget estimate",
        "",
        f"Closed episodes: {n_episodes}",
        "",
        (
            f"Haiku estimate (`{settings.news_model}`, "
            f"{settings.news_estimate_searches_per_episode} searches/episode, "
            f"{settings.news_estimate_input_tokens_per_episode} input + "
            f"{settings.news_estimate_output_tokens_per_episode} output tokens/episode): "
            f"${_usd(haiku_estimate)}"
        ),
        "",
        (
            "Worst case at hard caps (every episode uses "
            f"{settings.news_max_searches_per_request} searches and the "
            f"${_usd(settings.news_episode_cost_reserve_usd)} per-episode reserve):"
        ),
        f"- Search cost at the cap: ${_usd(worst_case_search)}",
        f"- Reserve headroom: ${_usd(worst_case_reserve)}",
        "",
        (
            f"Escalation scenario (re-running {n_escalate} episodes, "
            f"~{int(_ESCALATION_FRACTION * 100)}% of {n_episodes}, on "
            f"`{settings.news_escalation_model}`): ${_usd(escalation_estimate)}"
        ),
        "",
        f"Budget cap: ${_usd(settings.news_budget_usd)}",
        "",
    ]


def _ledger_section(ledger: list[dict], settings) -> list[str]:
    lines = ["## Actual spend", ""]
    if not ledger:
        lines += ["No paid runs recorded yet.", ""]
        return lines

    lines += [
        "| run_id | mode | model | episodes_written | searches | cost |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for entry in ledger:
        lines.append(
            f"| {entry['run_id']} | {entry['mode']} | {entry['model']} | "
            f"{entry['episodes_written']} | {entry['web_search_requests']} | "
            f"${_usd(entry['cost_usd'])} |"
        )
    total = ledger_total_usd(ledger)
    remaining = settings.news_budget_usd - total
    lines += [
        "",
        f"Total spent: ${_usd(total)}",
        f"Remaining budget: ${_usd(remaining)}",
        "",
    ]
    return lines


def render_budget(n_episodes: int, ledger: list[dict], settings) -> str:
    """Render docs/PHASE3_BUDGET.md's full content as a string. Pure -- no I/O, no
    datetime.now(); every value comes from `n_episodes`, `ledger` or `settings`, so two
    calls with the same arguments always produce byte-identical output."""
    lines = ["# Phase 3 news enrichment budget", "", HEADER, ""]
    lines += _pricing_section(settings)
    lines += _estimate_section(n_episodes, settings)
    lines += _ledger_section(ledger, settings)
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes-path", default=str(SETTINGS.episodes_path))
    parser.add_argument("--ledger-path", default=str(SETTINGS.news_spend_ledger_path))
    parser.add_argument("--out", default=str(OUTPUT_PATH))
    args = parser.parse_args(argv)

    episodes = load_episodes(Path(args.episodes_path))
    n_episodes = int((episodes["status"] == "closed").sum())
    ledger = load_spend_ledger(Path(args.ledger_path))

    report = render_budget(n_episodes, ledger, SETTINGS)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
